### ISSUE TITLE
subiquitycore crash when user-data contains wifis in netplan

### ISSUE THREAD

**Issue by dnck** [covertsh/ubuntu-autoinstall-generator#1]
Hi, I just tried this, and as title says, subiquitycore crashes when the user-data contains wifis in network section. Is this supposed to only work when the machine is plugged into ethernet? I should also mention that I was supplying user-data via a seperately mounted volume, not baked in.

**Comment by covertsh** [comment]
Hi. In my own testing, I've found that WiFi doesn't work using the server ISO - even when doing a live (non-auto) install, I can't set up my WiFi connection because it doesn't appear in the list of interfaces during network selection. This is the case with a few different chipsets, mostly Intel which are built into my laptops. Trying to configure these during the installation using the autoinstall data causes crashes for me too.

A workaround that I have been using is to use `cloud-init` to add a netplan configuration file to the target. This is a complete example of a user-data file that works on my laptop to create an Ubuntu 20.04 desktop. Since I add packages during the installation, this does require an ethernet connection during the build. For this particular issue, I don't think it matters whether you use a baked-in autoinstall config or attach one externally.

```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-laptop
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: covertsh
  packages:
    - ubuntu-desktop
  late-commands:
    - curtin in-target -- apt remove -y gnome-initial-setup
  user-data:
    write_files:
      - content: |
          network:
            version: 2
            renderer: NetworkManager
            wifis:
              wlp4s0:
                dhcp4: yes
                dhcp6: yes
                access-points:
                  "MyWiFiSSID":
                     password: "thewifipassword"
        path: /etc/netplan/00-installer-config.yaml
        permissions: '0644'
        owner: root:root
```
