### ISSUE TITLE
How to supply network-config

### ISSUE THREAD

**Issue by VishalM8085** [covertsh/ubuntu-autoinstall-generator#15]
First of all this is not issue but looking for help actually.
I have network config which is generally hosted by netplan dir. so question is how can i pass that information during ISO creation? my feeling is it should be part of meta data but dont have clue about how to do it (Just passing network.yml as -m flag will work or not)

Here is the network config which I want to push as part of auto install so new machine will have management IP for the communication.
 network:
    renderer: networkd
    ethernets:
      eno1:
        dhcp4: true
      eno2:
        dhcp4: true
      eno3:
        dhcp4: false
        addresses: [172.16.1.26/24]
        gateway4: 172.16.1.50
        nameservers:
          addresses: [8.8.8.8, 4.2.2.2]
      eno4:
        dhcp4: true
      ens1f0:
        dhcp4: false
      ens1f1:
        dhcp4: false
      ens3f0:
        dhcp4: false
      ens3f1:
        dhcp4: false

    version: 2

**Comment by covertsh** [comment]
Hi, thank you for your question. Here is an example user-data file which could do what you need. It uses the ```write_files``` directive in cloud-init to create a ```netplan``` configuration file on the new installation. Of course you need to customize this with your own password hash and so on:

```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: ubuntu
  locale: en_US.UTF-8
  keyboard:
    layout: us
  user-data:
    write_files:
      - content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eno1:
                dhcp4: true
              eno2:
                dhcp4: true
              eno3:
                dhcp4: false
                addresses: [172.16.1.26/24]
                gateway4: 172.16.1.50
                nameservers:
                  addresses: [8.8.8.8, 4.2.2.2]
              eno4:
                dhcp4: true
              ens1f0:
                dhcp4: false
              ens1f1:
                dhcp4: false
              ens3f0:
                dhcp4: false
              ens3f1:
                dhcp4: false
        path: /etc/netplan/00-installer-config.yaml
        permissions: '0644'
        owner: root:root
```
It would be great if you can report back if this solves your issue. This is actually how I use Ubuntu autoinstalls on my laptop, except that I configure a WiFi network during the installation.
