### ISSUE TITLE
Packages added in user-data causes error

### ISSUE THREAD

**Issue by jby** [covertsh/ubuntu-autoinstall-generator#22]
I'm trying to add the 'ubuntu-desktop' package in my user-data file, however it ends up with an error during the cloud install:

```
waiting for cloud-init...
finish: subiquity/Package/load_autoinstall_data: 'ubuntu-desktop' is not of type 'array'

Failed validating 'type' in schema:
    {'items': {'type: 'string'}, 'type': 'array'}
    
On instance:
    'ubuntu-desktop'
An error occurred. Press enter to start shell
```

I don't think that it in any way is caused by your script, but I'm hoping that you might know what I've done wrong.

My 'user-data'-file:
```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ai-test
  interactive-sections:
    - storage
  packages:
    ubuntu-desktop
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
```
