### ISSUE TITLE
Autoinstall not working

### ISSUE THREAD

**Issue by Hamsterman** [covertsh/ubuntu-autoinstall-generator#3]
I build the ISO with success with a user-data file from a manual installation.

When I boot the newly created ISO in my virtual machine it can boot just fine.
But it is not autoinstalling. It prompts me for language selection.

**Comment by covertsh** [comment]
The ISO creation definitely works for many people so I suspect there is an issue specific to your setup. Please could you share some more information, including your user-data file? Which operating system are you using to create the autoinstall ISO?

**Comment by Hamsterman** [comment]
1) I am using Hyper-V to install a fresh Ubuntu 20.04 in a VM.
2) Using that new Ubuntu installation I create the custom ISO with my userfile (name change so I could attach it here)
3) I am using Hyper-V to run the custom ISO. I simply plug it in a new VM the exact same way as I did in step 1

[user-data.txt](https://github.com/covertsh/ubuntu-autoinstall-generator/files/5924549/user-data.txt)

**Comment by covertsh** [comment]
Thank you. Are you allowing the script to download an original Ubuntu ISO image or are you downloading it separately, then supplying it to the script with the "-s" option?

**Comment by Hamsterman** [comment]
It's downloading the ISO automatically

**Comment by covertsh** [comment]
OK, thanks. Ideally I would like to see the ISO file that is being created. Do you think you can upload it anywhere for me to download? I understand if this is not possible.

**Comment by Hamsterman** [comment]
Made a fresh one with: 

bash ubuntu-autoinstall-generator.sh -a -u user-data

https://we.tl/t-PrxjlgSzM0
(expires in 7 days)

**Comment by covertsh** [comment]
Thank you very much for your assistance. I booted a Hyper-V VM using that ISO and I also saw the language selection screen. I used the console to read the installer log from /var/log/cloud-init-output.log and this is what I found:
![image](https://user-images.githubusercontent.com/45894800/107006658-635aaf00-6789-11eb-9b42-04f0716b6639.png)

I think you need to format your user-data file like this:

```
identity:
  hostname: ubuntudocker
  password: "$6$......"
  realname: "your_realname"
  username: "your_username"
```

It seems like different YAML syntax is not being parsed correctly by cloud-init.

**Comment by covertsh** [comment]
You would also need to change the other sections of your user-data file to use the "simple" syntax, including keyboard and storage sections.

**Comment by Hamsterman** [comment]
Okay - I will give it a try. It seems that the auto generated user-data file from the official Ubuntu install is not working. Scary!

Also I did not know about the /var/log/cloud-init-output.log file.

I will return!

**Comment by covertsh** [comment]
I think you will need to change your storage section to not rely on serial numbers or WWN identifiers because those will change when you create a new virtual machine too.

**Comment by Hamsterman** [comment]
I can't figure out how to access the /var/log/cloud-init-output.log file when I am stuck at the language selection page.

**Comment by covertsh** [comment]
You can use the keyboard combinations Ctrl-Alt-F2 up to Ctrl-Alt-F6 to access virtual consoles during the installation. Ctrl-Alt-F1 will take you back to the original screen. On the virtual consoles you will be logged in automatically.

**Comment by Hamsterman** [comment]
Thank you - I have now passed the language selection screen.
I am trying to create a working user-data file but it is stuck a later point now I can see.

I will keep the issue open a couple of days more and close it when I got a working user-data file (for the next guy with issues like me)

**Comment by Hamsterman** [comment]
Here is a working user-data file

```
#cloud-config
autoinstall:
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://dk.archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  identity: 
        hostname: ubuntutest
        password: $6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0
        realname: ubuntu
        username: ubuntu
  keyboard:
        layout: dk
        toggle: null
        variant: ''
  locale: C
  snaps:
    - name: powershell
      classic: true
    - name: docker
  network:
    ethernets:
      eth0: 
        dhcp4: true
    version: 2
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    layout:
      name: direct
  version: 1
```
