### ISSUE TITLE
Storage configuration

### ISSUE THREAD

**Issue by pat0s** [covertsh/ubuntu-autoinstall-generator#6]
Hi, 
it is possible to configure storage interactively during installation using your method?

**Comment by covertsh** [comment]
Hi, yes it is totally possible. Here is an example user-data file with interactive storage (modified from the user-data.example file in this repository):

```
#cloud-config
autoinstall:
  version: 1
  interactive-sections:
   - storage
  identity:
    hostname: ubuntu-server
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: ubuntu
```

Have a look at https://ubuntu.com/server/docs/install/autoinstall-reference where you will find documentation for the user-data file, including how to make sections interactive during installation.
